# 预设模型文件列表
# 这个文件包含了用户可以选择的预设模型文件
# 每个模型包含下载所需的参数和元数据信息

preset_models:
  # 文本生成模型
  # - id: "hugging_face:meta-llama/Llama-2-7b-hf"
  #   name: "Llama 2 7B"
  #   description: "Meta的Llama 2 7B参数模型，适用于文本生成任务"
  #   category: "text-generation"
  #   source: "HUGGING_FACE"
  #   huggingface_repo_id: "meta-llama/Llama-2-7b-hf"
  #   huggingface_filename: "model.safetensors"
  #   size: 13800000000  # 约13.8GB
  #   tags: ["llama", "text-generation", "7b"]
  #   recommended: true

  # - id: "hugging_face:meta-llama/Llama-2-13b-hf"
  #   name: "Llama 2 13B"
  #   description: "Meta的Llama 2 13B参数模型，更强的文本生成能力"
  #   category: "text-generation"
  #   source: "HUGGING_FACE"
  #   huggingface_repo_id: "meta-llama/Llama-2-13b-hf"
  #   huggingface_filename: "model.safetensors"
  #   size: 25600000000  # 约25.6GB
  #   tags: ["llama", "text-generation", "13b"]
  #   recommended: false

  # - id: "hugging_face:codellama/CodeLlama-7b-hf"
  #   name: "Code Llama 7B"
  #   description: "专门用于代码生成的Llama 2变体"
  #   category: "code-generation"
  #   source: "HUGGING_FACE"
  #   huggingface_repo_id: "codellama/CodeLlama-7b-hf"
  #   huggingface_filename: "model.safetensors"
  #   size: 13800000000  # 约13.8GB
  #   tags: ["llama", "code-generation", "7b"]
  #   recommended: true

  # # 嵌入模型
  # - id: "hugging_face:text-embedding-ada-002"
  #   name: "Text Embedding Ada 002"
  #   description: "OpenAI的文本嵌入模型，适用于语义搜索和相似度计算"
  #   category: "embedding"
  #   source: "HUGGING_FACE"
  #   huggingface_repo_id: "text-embedding-ada-002"
  #   huggingface_filename: "model.safetensors"
  #   size: 1500000000  # 约1.5GB
  #   tags: ["embedding", "openai", "ada"]
  #   recommended: true

  # # Ollama模型
  # - id: "ollama_library:llama2"
  #   name: "Llama 2 (Ollama)"
  #   description: "通过Ollama库提供的Llama 2模型"
  #   category: "text-generation"
  #   source: "OLLAMA_LIBRARY"
  #   ollama_library_model_name: "llama2"
  #   size: 13800000000  # 约13.8GB
  #   tags: ["llama", "ollama", "text-generation"]
  #   recommended: true

  # - id: "ollama_library:mistral"
  #   name: "Mistral (Ollama)"
  #   description: "Mistral AI的7B参数模型，通过Ollama提供"
  #   category: "text-generation"
  #   source: "OLLAMA_LIBRARY"
  #   ollama_library_model_name: "mistral"
  #   size: 13800000000  # 约13.8GB
  #   tags: ["mistral", "ollama", "text-generation"]
  #   recommended: true

  # # 多模态模型
  # - id: "hugging_face:llava-hf/llava-1.5-7b-hf"
  #   name: "LLaVA 7B"
  #   description: "多模态模型，支持图像理解和文本生成"
  #   category: "multimodal"
  #   source: "HUGGING_FACE"
  #   huggingface_repo_id: "llava-hf/llava-1.5-7b-hf"
  #   huggingface_filename: "model.safetensors"
  #   size: 13800000000  # 约13.8GB
  #   tags: ["llava", "multimodal", "vision", "7b"]
  #   recommended: false

  # 语音模型
  - id: "model_scope:openai-mirror/whisper-base"
    name: "whisper-base(ModelScope)"
    description: "Whisper 是一个用于自动语音识别（ASR）和语音翻译的预训练模型"
    category: "speech-to-text"
    source: "MODEL_SCOPE"
    model_scope_model_id: "openai-mirror/whisper-base"
    model_scope_file_path: "model.safetensors"
    size: 304506470 # 约300MB
    tags: ["whisper", "speech-to-text", "modelscope", "damo", "chinese"]
    recommended: true