"""add_preset_model_fields_to_model_files

Revision ID: 431ec0706ef1
Revises: add_preset_model_fields
Create Date: 2025-06-30 11:14:23.577842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431ec0706ef1'
down_revision: Union[str, None] = 'add_preset_model_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
