"""Add status field to apps table

Revision ID: add_status_field_to_apps
Revises: add_app_management_tables
Create Date: 2025-01-21 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import aistack


# revision identifiers, used by Alembic.
revision: str = 'add_status_field_to_apps'
down_revision: Union[str, None] = 'add_app_management_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'status')
    # ### end Alembic commands ### 