"""add preset model fields to model_files

Revision ID: add_preset_model_fields
Revises: b1740c7371e5
Create Date: 2025-01-21 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'add_preset_model_fields'
down_revision: Union[str, None] = 'b1740c7371e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_files', sa.Column('is_preset_model', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('model_files', sa.Column('preset_model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('model_files', sa.Column('preset_model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('model_files', sa.Column('preset_model_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('model_files', sa.Column('preset_model_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('model_files', sa.Column('preset_model_tags', sa.JSON(), nullable=True))
    op.add_column('model_files', sa.Column('preset_model_recommended', sa.Boolean(), nullable=True))
    
    # 创建索引
    op.create_index(op.f('ix_model_files_is_preset_model'), 'model_files', ['is_preset_model'], unique=False)
    op.create_index(op.f('ix_model_files_preset_model_id'), 'model_files', ['preset_model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_files_preset_model_id'), table_name='model_files')
    op.drop_index(op.f('ix_model_files_is_preset_model'), table_name='model_files')
    op.drop_column('model_files', 'preset_model_recommended')
    op.drop_column('model_files', 'preset_model_tags')
    op.drop_column('model_files', 'preset_model_category')
    op.drop_column('model_files', 'preset_model_description')
    op.drop_column('model_files', 'preset_model_name')
    op.drop_column('model_files', 'preset_model_id')
    op.drop_column('model_files', 'is_preset_model')
    # ### end Alembic commands ### 