apiVersion: v1
kind: Service
metadata:
  name: example-ai-app
  labels:
    app: example-ai-app
    managed-by: aistack
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: example-ai-app

