apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx2
  labels:
    app: demo-nginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-nginx2
  template:
    metadata:
      labels:
        app: demo-nginx2
    spec:
      containers:
        - name: nginx2
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web-root
              mountPath: /usr/share/nginx/html
      volumes:
        - name: web-root
          hostPath:
            path: /run/desktop/mnt/host/d/data/nginx-html  # 对应 Windows 的 C:\data\nginx-html
            type: DirectoryOrCreate